### ISSUE TITLE
Create our Code standards/style guide 

### ISSUE THREAD

**Issue by gmoura** [Laboratoria/developers.laboratoria.la#11]
Hi guys, 

We could create our code standards/style guide for Javascript, CSS and HTML or maybe we could follow some good one like these ones:

## By Airbnb:

* [CSS Style guide](https://github.com/airbnb/css)
* [Javascript](https://github.com/airbnb/javascript)

## By Google:

* [CSS and HTML](https://google.github.io/styleguide/htmlcssguide.html)
* [Javascript](https://google.github.io/styleguide/jsguide.html)

What do you think guys?

**Comment by merunga** [comment]
hi @gmoura 
I think that starting one from scratch is a HUGE effort
Taking into account the amount of linting rules that are out there, I think that we should grab an existing standrad and tweak only the rules that we think are relevant for us... the airbnb one is kind of a defacto standard right now in js.

**Comment by gmoura** [comment]
I totally agree with you @merunga about starting from scratch.

Could we fork Airbnb Javascript and CSS style guide and adapt to our context, what do you think?

**Comment by merunga** [comment]
@gmoura don't you think it might be easier to have the airbnb packages as dependecies, and extend / overwrite those defaults, instead of forking? Eslint presets already understand the "extends" concept.

Dependencies are more flexible than forks I think, and is the way other projects are doing this. Here's [an example](https://github.com/DataPipelineInc/eslint-config-datapipeline/blob/master/index.js).

What do you think about this approach?

**Comment by gmoura** [comment]
@merunga Yehh I like the idea! ❤️ 

About "fork"  I tryed to say this [Laboratory Javascript Style Guide](https://hungry-borg-b29086.netlify.com/coding/). Have in somewhere a document that every developer in Laboratoria would/need to follow and know about

I like the idea is every developer in Laboratoria code in the same way,

**Comment by lupomontero** [comment]
I totally agree with the idea of adopting the [Airbnb's JavaScript Style Guide](https://github.com/airbnb/javascript) and enforcing it with Eslint using the [eslint-config-airbnb-base](https://www.npmjs.com/package/eslint-config-airbnb-base) for non React projects, and their [React/JSX Style Guide](https://github.com/airbnb/javascript/tree/master/react) when appropriate (see [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)).

On the other hand, wrt CSS, I'm open to suggestions, but since we are adopting Airbnb's for JavaScript it might make sense to do the same for CSS. Thoughts?

:muscle:

**Comment by gmoura** [comment]
@lupomontero About CSS 

https://hungry-borg-b29086.netlify.com/code-standards/css-style-guide/

**Comment by lupomontero** [comment]
Based on this thread and previous conversations, I have gone ahead and updated this repo's [`README.md`](https://github.com/Laboratoria/developers.laboratoria.la#coding-standards) with the agreed coding standards so far.
