### ISSUE TITLE
Create content for Github workflow

### ISSUE THREAD

**Issue by gmoura** [Laboratoria/developers.laboratoria.la#13]

**Comment by gmoura** [comment]
Proposal
https://hungry-borg-b29086.netlify.com/code-standards/github-workflow/

**Comment by lupomontero** [comment]
Hi @gmoura, I have reopened this issue so that we can continue the discussion here :wink:

I like [the proposal](https://github.com/Laboratoria/developers.laboratoria.la#coding-standards) :+1: 

The only thing I would like to comment on is the commit conventions as I would like to consider https://gist.github.com/stephenparish/9941e89d80e2bc58a153

Could you add the proposed workflows to the [`README.md`](https://github.com/Laboratoria/developers.laboratoria.la/blob/master/README.md) and send a PR so that we can discuss independently from [the other open PR](https://github.com/Laboratoria/developers.laboratoria.la/pull/19)?

**Comment by lupomontero** [comment]
cc/ @bouli

**Comment by lizzie136** [comment]
Hello @gmoura!, I like the proposal, it's quite simple and yet something we need, still have some comments:

- About the _commit messages_, I used something similar to your proposal, but I get we need to be clear from the begging what do the commit, so having tokens at the beginning of the commit name may help to get us in context. Similar to what Lupo's conventions mentioned. Maybe we can use a more simplified way. I prefer to have at least 100 characters for the visible message, and then the proper description. In case of bullet points or hyphens, to have two spaces before the (-) and one after. 

- About the tokens for the commit, not sure if having WIP technically is needed, since every branch is a WIP until a PR is sent. Except, of course, specific cases as branches to maintain more than one version and those will need other names. I would add maybe fix, or as another flavor, the module name if the architecture let us.

**Comment by gmoura** [comment]
#22

**Comment by lupomontero** [comment]
Closing this issue as https://github.com/Laboratoria/developers.laboratoria.la/pull/22 has now been merged :rocket:
